FROM prom/prometheus:v2.51.0
COPY monitoring/prometheus.yml /etc/prometheus/prometheus.yml
ENTRYPOINT []
CMD ["sh", "-c", "\
  echo \"$GRAFANA_CLOUD_TOKEN\" > /etc/prometheus/grafana_token && \
  /bin/prometheus \
  --config.file=/etc/prometheus/prometheus.yml \
  --storage.tsdb.path=/prometheus \
  --web.console.libraries=/usr/share/prometheus/console_libraries \
  --web.console.templates=/usr/share/prometheus/consoles \
  --web.listen-address=:${PORT:-9090}"]
