services:
  postgres:
    image: postgres:16-alpine
    container_name: erp-vendas-db
    environment:
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp123
      POSTGRES_DB: erp_vendas
    ports:
      - "5432:5432"
    volumes:
      - erp_pgdata:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: erp-vendas-prometheus
    profiles: [monitoring]
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'

  grafana:
    image: grafana/grafana:10.4.2
    container_name: erp-vendas-grafana
    profiles: [monitoring]
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

volumes:
  erp_pgdata:
  prometheus_data:
  grafana_data:
