global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'erp-vendas-api'
    scheme: https
    static_configs:
      - targets: ['sige-erp-vendas-api-production.up.railway.app']
    metrics_path: '/metrics'
