name: Load Test

on:
  schedule:
    - cron: '0 11 * * *'  # 08:00 BRT
    - cron: '0 16 * * *'  # 13:00 BRT
    - cron: '0 22 * * *'  # 19:00 BRT
  workflow_dispatch:       # permite rodar manualmente pelo GitHub

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: grafana/setup-k6-action@v1

      - name: Run load test
        run: k6 run k6/load-test.js || true
